### PR TITLE
file-handler.js - reference error missing _this

### PR DESCRIPTION
**Pull request by ghost**
Hey there,
I am using aurelia-files with requirejs. I assigned a or-error-handler which cannot be found. It's probably caused by this file:
https://github.com/grofit/aurelia-files/blob/master/dist/amd/handlers/file-handler.js
in line 73: 
`if (onError) {`
which should probably look like this:
`if (_this.onError) {`

I don't know if/how to use the build system, so I changed the file directly. Hope that's all right.

### CODE REVIEW

**Comment by grofit** [comment]
wasnt this fixed a while back? let me check the commits.

**Comment by grofit** [comment]
Yes it was, it just looks like the dist files were not refreshed so I will do that and push up as this change would get overridden the moment someone builds anyway.

**Comment by itfourp** [comment]
Great, thank you!

**Comment by grofit** [comment]
All done, should be fine in 0.1.2

**Pull request closed without merging**
