### PR TITLE
Prevent undefined errors

### PR DESCRIPTION
**Pull request by roelplieger**
I had a situation where handleFileSelected was called where fileSelectionEvent.target was undefined, this resulted in a javascript error.

### CODE REVIEW

**Comment by grofit** [comment]
Thanks for the PR have merged it in

**Comment by roelplieger** [comment]
Can you please create a new tag for this version? Otherwise I cannot build it using your updated repo :-)
Tx!

**Comment by grofit** [comment]
https://github.com/grofit/aurelia-files/releases/tag/0.1.4

done

**Comment by roelplieger** [comment]
Hi, could you also please update de version in https://www.npmjs.com/package/aurelia-files? Tx again :-)

**Comment by grofit** [comment]
oh sure, I will try and do it tonight, didnt know I had put it on npm (sorry for delay everyone at home was ill)

**Comment by roelplieger** [comment]
ok, thanks! hope you are ok now :-)

**Comment by grofit** [comment]
all done 0.1.4 is up there

**Comment by roelplieger** [comment]
GREAT :-)

**Comment by roelplieger** [comment]
Hi, discovered a problem in this version, you probably didn't do a gulp build, the new code isn't in the transpiled files! You can see this in dist/amd/handlers/file-handler.js in the this.handleFileSelected() method, this still contains the old transpiled code.

**Comment by grofit** [comment]
meh, will try to do this for you when I get on later, thanks for the info.

**Comment by grofit** [comment]
Have gulped and uploaded new dist... forgot how painful it all was :(

**Comment by roelplieger** [comment]
Thanks!

**Pull request merged**
